name: Penn Data Science Group
description: Official website for the Penn Data Science Group at UPenn
url: http://penndsg.github.io

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
